### ISSUE TITLE
Unable to find ffnn.pkl file

### ISSUE THREAD

**Issue by lthakur007** [nzc/dnn_ctr#14]
Hi, 
Could you please help me fix the following issue.
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from model import FNN
  File "/root/dnn-ctr-fnn/dnn_ctr/model/FNN.py", line 540, in <module>
    fnn.load_state_dict(torch.load('./data/model/ffnn.pkl'))
  File "/root/.local/lib/python2.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: './data/model/ffnn.pkl'

**Comment by nzc** [comment]
@luckynikki This is my fault. You are supposed to Document the code in line 540 (fnn.load_state_dict(torch.load('./data/model/ffnn.pkl'))) and use the code in line 541 to pretrain the fm model and save it.

**Comment by lthakur007** [comment]
Thank you for the help. It worked :).
