### ISSUE TITLE
关于DCN

### ISSUE THREAD

**Issue by CXY573** [nzc/dnn_ctr#8]
首先，感谢分享，原文有一句话是We propose the DCN model that enables Web-scale automatic feature learning with both sparse and dense inputs 是可以把稀疏数据作为训练数据的，请问你的分享是否有这样的接口呢。

**Comment by CXY573** [comment]
我说的是稀疏表示的矩阵，sparse库里面的那种表示，而不是稠密表示的稀疏矩阵

**Comment by CXY573** [comment]
还有一个问题 为什么我按
m = dcn.predict_proba(test_dict['index'],test_dict['value'])
做预测 得到了如下错误：
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "DCN.py", line 562, in <module>
    m = dcn.predict_proba(test_dict['index'],test_dict['value'])
  File "DCN.py", line 513, in predict_proba
    pred = F.sigmoid(model(Xi, Xv)).cpu()
  File "/home/cxy/.conda/envs/python2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "DCN.py", line 243, in forward
    fm_wij_arr.append(torch.sum(emb_arr[i] * emb_arr[j],1).view([-1,1]))
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58
@nzc

**Comment by CXY573** [comment]
[1,   100] loss: 583.635897 metric: 0.591613 time: 15.8 s
**************************************************
[1] loss: 22.228953 metric: 0.616724 time: 19.0 s
**************************************************
**************************************************
[1] loss: 22.255722 metric: 0.614940 time: 20.2 s
**************************************************
[2,   100] loss: 88.273439 metric: 0.584751 time: 14.7 s
**************************************************
[2] loss: 29.329584 metric: 0.622159 time: 17.9 s
**************************************************
**************************************************
[2] loss: 29.419680 metric: 0.619503 time: 19.1 s
**************************************************
[3,   100] loss: 45.896620 metric: 0.574566 time: 13.4 s
**************************************************
[3] loss: 34.074569 metric: 0.587830 time: 16.7 s
**************************************************
**************************************************
[3] loss: 34.868626 metric: 0.584307 time: 17.8 s
**************************************************
[4,   100] loss: 35.304552 metric: 0.573835 time: 14.0 s
**************************************************
[4] loss: 44.318500 metric: 0.564652 time: 16.6 s
**************************************************
**************************************************
[4] loss: 44.822131 metric: 0.561964 time: 17.8 s
**************************************************
[5,   100] loss: 28.368226 metric: 0.526387 time: 13.9 s
**************************************************
[5] loss: 74.812706 metric: 0.538661 time: 16.9 s
**************************************************
**************************************************
[5] loss: 75.696912 metric: 0.537339 time: 18.1 s
**************************************************

这个loss怎么是往上升的 作者能回复一下吗。。。@nzc

**Comment by nzc** [comment]
@CXY573 可能是由于数据集太小导致的。也有可能是dcn前面几轮是很难收敛的。会出现抖动。
